# Generated by Django 6.0.1 on 2026-02-23 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='blocked_status',
            field=models.CharField(choices=[('active', 'Активный'), ('blocked', 'Заблокированный'), ('hidden', 'Скрытый'), ('unhide', 'Раскрыть')], default='unhide', max_length=7),
        ),
    ]
